name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Pokemon/Pokemon.sln
      Publish_Directory: publish

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore and Build
      run: |
        dotnet restore ${{ env.Solution_Name }}
        dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Publish Blazor Server Application
      run: dotnet publish ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --output ${{ env.Publish_Directory }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifact-${{ matrix.configuration }}
        path: ${{ env.Publish_Directory }}
