name: Code Linter2
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  lint:
    runs-on: windows-latest
 
    env:
      Solution_Name: Pokemon.sln
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
 
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
 
    - name: Install CSharpier
      run: dotnet tool install --global csharpier
 
    - name: Linting solution
      run: dotnet csharpier --check .
