name: Code Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: windows-latest

    env:
      Solution_Name: Pokemon/Pokemon.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore .NET tools
      run: dotnet tool restore
    
    - name: Install CSharpier
      run: dotnet tool install --global csharpier
      env:
        DOTNET_ROOT: C:\Users\runneradmin\.dotnet
    
    - name: Linting solution
      run: dotnet csharpier --check .
      env:
        PATH: C:\Users\runneradmin\.dotnet\tools;${{ env.PATH }}
