name: Code Format Check

on: [push, pull_request]

env:
  Solution_Name: Pokemon/Pokemon.sln
  Publish_Directory: publish

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Code Format überprüfen
      run: dotnet format ${{ env.Solution_Name }} --verify-no-changes

    - name: Build Project
      run: dotnet build ${{ env.Solution_Name }}
