name: Blazor Server Application

on:
  push:
    branches: [ "master" ]  # Trigger the workflow on pushes to the master branch
  pull_request:
    branches: [ "master" ]  # Trigger the workflow on pull requests to the master branch

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]  # Define build configurations (Debug and Release)

    runs-on: windows-latest  # Use the latest Windows runner

    env:
      Solution_Name: your-solution-name.sln  # Name of the solution file
      #Test_Project_Path: your-test-project-path  # Path to the test project
      Publish_Directory: your-publish-directory  # Directory to publish the build artifacts

    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Checkout the repository
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4  # Setup .NET Core
      with:
        dotnet-version: 9.0.x  # Install .NET Core version 9.0.x

   # - name: Execute unit tests
   #   run: dotnet test ${{ env.Test_Project_Path }}  # Run unit tests

    - name: Restore and Build
      run: |
        dotnet restore ${{ env.Solution_Name }}  # Restore dependencies
        dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}  # Build the solution with the specified configuration
      env:
        Configuration: ${{ matrix.configuration }}  # Pass the configuration to the environment

    - name: Publish Blazor Server Application
      run: dotnet publish ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --output ${{ env.Publish_Directory }}  # Publish the application
      env:
        Configuration: ${{ matrix.configuration }}  # Pass the configuration to the environment

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4  # Upload build artifacts
      with:
        name: Build Artifact  # Name the artifact
        path: ${{ env.Publish_Directory }}  # Specify the path to the artifacts
