name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: windows-latest

    env:
      Solution_Name: Pokemon/Pokemon.sln
      Publish_Directory: publish

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore and Build
      run: |
        dotnet restore ${{ env.Solution_Name }}
        dotnet build ${{ env.Solution_Name }} --configuration Release
      env:
        Configuration: Release

    - name: Publish Blazor Server Application
      run: dotnet publish ${{ env.Solution_Name }} --configuration Release --output ${{ env.Publish_Directory }}
      env:
        Configuration: Release

    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release Artifact
        path: ${{ env.Publish_Directory }}

    - name: Create Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
        git push origin "v${{ github.run_number }}"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Release notes for v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
